name: mobile_banking
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Base
  cupertino_icons: ^1.0.3
  nb_utils: ^4.5.2
  #intl: ^0.18.0
  flutter_vector_icons: ^2.0.0
  google_fonts: ^3.0.1

  mobx: ^2.0.3
  flutter_mobx: ^2.0.1

  # Wallet App
  cached_network_image: ^3.2.0
  fl_chart: ^0.55.2
  otp_text_field: ^1.1.3
  dots_indicator: ^2.0.0
  scan: 1.6.0
  get: ^4.6.5
  flutter_session_manager: ^1.0.3
  rflutter_alert: ^2.0.4
  slider_button: ^2.0.0
  syncfusion_flutter_charts: ^20.4.54
  flutter_svg: ^1.1.6
  flutter_staggered_grid_view: ^0.6.2
  html: ^0.15.1
  carousel_slider: ^4.2.1
  gif_view: ^0.3.0
  fading_image_button: ^0.10.0+0
  image_picker: ^0.8.6
  local_auth: ^2.1.3
  url_launcher: ^6.1.7
  smooth_page_indicator: ^1.0.0+2
  #pdf: ^3.8.4
  #pdf_viewer_plugin: ^2.0.1
  dio: ^4.0.6
  #printing: ^5.9.3
  showcaseview: ^2.0.0+1
  #pinput: ^2.2.21
  #pinput: ^2.2.21
  pinput:
   git:
    url: https://github.com/Tkko/Flutter_Pinput
    ref: dev
  video_player: ^2.5.1
  modal_progress_hud_nsn: ^0.3.0
  coupon_uikit: ^0.2.0
  flutter_fortune_wheel: ^1.2.0
  confetti: ^0.7.0
  country_picker: ^2.0.19
  percent_indicator: ^4.2.2
  screenshot: ^1.3.0
  social_share: ^2.3.1
  google_maps_flutter: ^2.2.4
  qr_flutter: ^4.0.0
  syncfusion_flutter_datepicker: ^20.4.53
  flutter_rounded_date_picker: ^3.0.2
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter
  material_floating_search_bar: ^0.3.7
  flutter_credit_card: ^3.0.6
  csc_picker: ^0.2.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.7



flutter:

  uses-material-design: true

  assets:
   - images/mobile_banking/
   - images/mobile_banking/smart_home/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

